### ISSUE TITLE
Accounting

### ISSUE THREAD

**Issue by Sprax2013** [HEMS-2020/Firmenparkplatzverwaltung#12]
Preise lassen sich jederzeit ändern

| Zeitraum | Preis in EUR |
| --- | --- |
| je 30min | 1,00 |
| je 60min | 3,00 |
| je 24h | 30,00 |
| Dauerhaft (pro Monat) | 250,00 |

* Manuell kann eine Rechnung erstelllt werden
  * Diese wird per Post **oder** Mail versandt

**Comment by tth05** [comment]
Needs to send E-Mails to each user.
