### ISSUE TITLE
GUI Design

### ISSUE THREAD

**Issue by Sprax2013** [HEMS-2020/Firmenparkplatzverwaltung#17]
* Parkplätze lassen sich anzeigen und verwalten
* RFID-Chips und Nutzer verwalten
* Suchfunktion
* Übersicht über freie/ belegte / ... Parkplätze
* Jeder Parkplatz hat ein Ampelsystem (Frei =Grün, Belegt =Rot, Vermietet =Blau, Defekt =Gelb)

**Comment by tth05** [comment]
I've mostly layed out the design, so I will close this for now
