### ISSUE TITLE
Users.txt löschen?

### ISSUE THREAD

**Issue by SpraxDev** [HEMS-2020/Firmenparkplatzverwaltung#67]
Soll https://github.com/HEMS-2020/Firmenparkplatzverwaltung/blob/master/java/Users.txt im repo sein oder ein Versehen? xD

**Comment by tth05** [comment]
ne weg damit

**Comment by SpraxDev** [comment]
*Geh schlafen Tim* Mi Mi Mi

**Comment by tth05** [comment]
nerv nich
